### ISSUE TITLE
Same mediatek chipset also in Samsung Tab A7 lite can i use this

### ISSUE THREAD

**Issue by alexmiller00** [Yahoo-Mike/recovery_device_lenovo_X606FA#2]
So I'm new to kernel building but I have the same mediatek chipset MT8768 helios p22t that IS In this Lenovo m10 fhd rev.2 and while I already have kali nethunter running on my magisk rooted A7 lite, I'm not getting quite the quality I believe would be achieved if I had a custom kernel with just a few device specific props. I also would want to have it compiled for the more popular wifi chipsets that support monitor mode, frame injection and promiscuous mode Like @kimocoder 's 
[RTL8812AU, RTL8821AU, RTL8814AU](https://github.com/kimocoder/rtl8812au) [ [RTL8192EU](https://github.com/kimocoder/rtl8192eu) [ RTL8188EU ](https://github.com/aircrack-ng/rtl8188eus)  and those found in the tp-link usb dongles [wdn-520](https://github.com/kimocoder/mt7610u_wifi_sta_v3002_dpo_20130916) 0 or wn-823n (commonly found at big box retail stores, easy to get the same day if necessary) anyways I'm hoping that someone can help me or at least point me in the right direction??

**Comment by Yahoo-Mike** [comment]
The opensource kernel for TB-X606F is available on [Lenovo's website](https://pcsupport.lenovo.com/uu/en/products/tablets/m-series-tablets/tab-m10-fhd-plus/downloads/ds543634-open-source-code-tab-m10-fhd-plus-tb-x606x-tb-x606f).
